name: Experiments

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Dump label
        env:
          GITHUB_LABEL: ${{ github.event.pull_request.head.label }}
        run: |
          echo "$GITHUB_LABEL"
          parts=$(echo $GITHUB_LABEL | tr ":" "\n")
          source_repo=${GITHUB_LABEL%:*}
          source_branch=${GITHUB_LABEL#*:}
          echo Should take a look at branch $source_branch from $source_repo.
