name: Experiments

on: [push, pull_request]

jobs:
  test:
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      # - name: Dump label
      #   env:
      #     GITHUB_LABEL: ${{ event.pull_request.head.label }}
      #   run: |
      #     echo "$GITHUB_LABEL"